NameError: name 'a' is not defined

In [19]:
import numpy as np

In [4]:
#1a
a = np.array([[[[2,3,4],[7, 8, 9]],[[2,3,4],[7, 8, 9]]]])

In [5]:
a.size

12

In [6]:
a.shape

(1, 2, 2, 3)

In [7]:
a.ndim

4

In [11]:
#1b
b = np.array([[[2,3,4]],[[7, 8, 9]]])


In [12]:
b.size

6

In [13]:
b.shape

(2, 1, 3)

In [14]:
b.ndim

3

In [15]:
c = np.array([[[[[2.0,4.6],[2.0,4.6],[2.0,4.6]],[[2.0,4.6],[2.0,4.6],[2.0,4.6]]]]]#2a
d = np.array())

In [16]:
c.size

12

In [17]:
c.shape

(1, 1, 2, 3, 2)

In [18]:
c.ndim

5

In [22]:
#2a   3-D array of three 2 by 2 innermost array with zero values
d = np.zeros((3, 2, 2))
#b. 4-D array of three 2 by 2 innermost array with zero values
e = np.zeros((1, 3, 2, 2))
#3-D  array of one 2 by 5 innermost array with the value of one
#throughout
f = np.ones((1, 2, 5))
#5-D array of two 2 by 2 innermost array with the value of
#one throughout
g = np.ones((1, 1, 2, 2, 2))
#8-D array of four 2 by 2 innermost with the value of one
#throughout
h = np.ones((1, 1, 1, 1, 1, 4, 2, 2))

In [25]:
#3
np.arange(100, 201, 10)

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200])

In [26]:

#
arrs = np.linspace(5, 25, num=5)
print(arrs)

[ 5. 10. 15. 20. 25.]


In [27]:
#bonus 
y2 = np.linspace(5, 25, num=5).reshape(5, 1)
print(y2)

[[ 5.]
 [10.]
 [15.]
 [20.]
 [25.]]


In [3]:
import numpy as np
#1. If x = [4,6,17,8,9,3,15,12,7,13] convert x to ndarray and print:
x = [4,6,17,8,9,3,15,12,7,13]
x1 = np.array(x)



[ 4  6 17  8  9  3 15 12  7 13]


In [4]:
#a. value 17 and 7 separately using their positive index
print(x1[2])

17


In [7]:
print(x1[8])

7


In [8]:
print(x1[-3])

12


In [9]:
print(x1[-5])

3


In [11]:
# the range  of values from 8 to 12 using positive indices
print(x1[3:8])

[ 8  9  3 15 12]


In [13]:
print(x1[-10:-3])

[ 4  6 17  8  9  3 15]


In [14]:
print(x1[2:])

[17  8  9  3 15 12  7 13]


In [15]:
print(x1[-9:])

[ 6 17  8  9  3 15 12  7 13]


In [16]:
print(x1[-8:6])

[17  8  9  3]


In [17]:
print(x1[-5:9])

[ 3 15 12  7]


In [19]:
print(x1[0:10])

[ 4  6 17  8  9  3 15 12  7 13]


In [23]:
print(x1[-10:])

[ 4  6 17  8  9  3 15 12  7 13]


In [24]:
print(x1[:])

[ 4  6 17  8  9  3 15 12  7 13]


In [25]:
print(x1[:8])

[ 4  6 17  8  9  3 15 12]


In [26]:
print(x1[1:])

[ 6 17  8  9  3 15 12  7 13]


In [15]:
import numpy as np
#Create a two dimensional array for numbers between 1 and 25. Using the array, find the following:
a = np.arange(1, 26, 1)
#1. all the even numbers



In [16]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [17]:
a1 = np.array([a])

In [18]:
print(a1)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25]]


In [19]:
type(a1)

numpy.ndarray

In [20]:
print(a1[a1%2==0])

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [21]:
print(a1[a1%4==0])

[ 4  8 12 16 20 24]


In [22]:
print(a1[100%a1==0])

[ 1  2  4  5 10 20 25]


In [26]:
print(a1[(a1<=5)|(a1>20)|(a1==15)])

[ 1  2  3  4  5 15 21 22 23 24 25]


In [24]:
print(a1[(a1%2==1)&(a1%6==0)])

[]


In [27]:
#a. Create a two dimensional array for numbers between 1 and 25.
import numpy as np
h = np.arange(1, 26).reshape(5, 5)

In [28]:
print(h)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [30]:
print(h[0])

[1 2 3 4 5]


In [32]:
#print all numbers in column 2
print(h[: ,1:2])

[[ 2]
 [ 7]
 [12]
 [17]
 [22]]


In [33]:
print(h[3:4,0:3])

[[16 17 18]]


In [34]:
print(h[3:5,0:3])

[[16 17 18]
 [21 22 23]]


In [35]:
print(h[2][2])

13


In [36]:
print(h[1:3])

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [38]:
print(h[:, 1:3])

[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]
 [22 23]]


In [2]:
#Create a 3-D numpy array with numbers from 1 to 72.
import numpy as np
a = np.arange(1,73).reshape(3, 4, 6)
#Using the above array, print:

In [3]:
print(a)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]
  [37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]
  [61 62 63 64 65 66]
  [67 68 69 70 71 72]]]


In [4]:
print(a[0][1][3])

10


In [5]:
print(a[0])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [6]:
print(a[1][1,0:6])

[31 32 33 34 35 36]


In [7]:
print(a[2][2,2:5])

[63 64 65]


In [8]:
print(a[1][1][4])

35


In [10]:
print(a[0][1][3])
print(a[1][1][3])
print(a[2][2][5])

10
34
66


In [12]:
print(a[0][:,2:3])

[[ 3]
 [ 9]
 [15]
 [21]]


In [13]:
print(a[1][1,3:5])

[34 35]


In [14]:
print(a)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]
  [37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]
  [61 62 63 64 65 66]
  [67 68 69 70 71 72]]]


In [15]:
print(a[2][0,:])

[49 50 51 52 53 54]


In [16]:
print(a[2])

[[49 50 51 52 53 54]
 [55 56 57 58 59 60]
 [61 62 63 64 65 66]
 [67 68 69 70 71 72]]


In [17]:
print(a[1][0,:])

[25 26 27 28 29 30]


In [20]:
print([:,5:6])

SyntaxError: invalid syntax (Temp/ipykernel_10588/3232479779.py, line 1)

In [23]:
print(a[:][0:4,5:6])

[]


In [25]:
print(a[:,:,5:])

[[[ 6]
  [12]
  [18]
  [24]]

 [[30]
  [36]
  [42]
  [48]]

 [[54]
  [60]
  [66]
  [72]]]


In [26]:
print(a[1:3,:,2:3])

[[[27]
  [33]
  [39]
  [45]]

 [[51]
  [57]
  [63]
  [69]]]


In [28]:
#16. number less than 50 in the 3rd column of the second and last 2-D in the 3-D
c=a[1:3,:,2:3]
print(c[c<50])
#print(a[1:3,:,2:3][a[1:3,:,2:3],50]) the same


[27 33 39 45]


In [29]:
#17. numbers that are divisible by 5 in column 2 of second and third 2-D in the 3-D array
a[1:3,:,1:2]


array([[[26],
        [32],
        [38],
        [44]],

       [[50],
        [56],
        [62],
        [68]]])

In [30]:
b = a[1:3,:,1:2]
print(b[b%5==0])

[50]
